#!/usr/bin/env python3
"""Generate privacy.html and terms.html from the canonical legal copy.
Mirrors Astryn/Models/LegalContent.swift. Re-run after editing the sections."""
import html
import hashlib


def _ver(path):
    try:
        with open(path, "rb") as fh:
            return hashlib.md5(fh.read()).hexdigest()[:8]
    except OSError:
        return "1"


CSS_VER = _ver("style.css")
JS_VER = _ver("app.js")

TERMS_UPDATED = "April 2026"
PRIVACY_UPDATED = "April 2026"
PRIVACY_COMMITMENT = ("Your privacy is fundamental to Astryn. We collect only "
                      "what's necessary and never sell your personal data.")

TERMS = [
("1. Acceptance of Terms", """By downloading, installing, or using Astryn ("the App"), you agree to be bound by these Terms and Conditions. You also confirm that you meet the eligibility and suitability requirements set out in Section 3 below. If you do not agree to these terms, or you do not meet those requirements, please do not use the App."""),
("2. Description of Service", """Astryn is a personal astrology and self-reflection application that provides natal chart calculation, daily and weekly cosmic guidance, lunar reflections, journaling, and AI-powered insights. It is intended for informational, educational, entertainment, and self-reflective purposes only.

The App is NOT:
• A medical device
• A mental health treatment, therapy, counselling service, or crisis service
• A substitute for advice or care from a qualified healthcare or mental-health professional
• A diagnostic or predictive tool of any kind

Astrological interpretations, insights, observations, and responses generated by the App, including by its AI features, are not clinical assessments or factual predictions and must not be relied on as such."""),
("3. Eligibility & Suitability", """The App is intended for adults aged 18 or over who are using it for general self-reflection and entertainment, and who are in a stable enough place to engage with self-directed reflection usefully.

By using the App you represent and warrant, on each occasion you use it, that:
• You are at least 18 years old;
• You are not currently in a mental health crisis, experiencing suicidal ideation or self-harm thoughts, or in a psychiatric emergency;
• You are not using the App as a substitute for, or in place of, prescribed treatment, medication, therapy, or any other professional intervention you have been advised to follow;
• You will not represent the App's content as a diagnosis, treatment plan, clinical opinion, or factual prediction of future events;
• Your use of the App will comply with applicable laws.

If any of the warranties above ceases to be true at any time, in particular, if you enter a crisis or an acute episode, you agree to stop using the App and to consult a qualified professional."""),
("4. Not Professional Advice", """The content, insights, suggestions, reflections, forecasts, and any AI-generated material produced by the App are for informational, educational, and entertainment purposes only. They do NOT constitute, and must not be interpreted as:
• Medical, mental health, clinical, or any form of healthcare advice;
• A diagnosis or screening for any condition;
• A recommendation regarding medication, treatment, therapy, or any clinical intervention;
• Legal, financial, or other professional advice;
• A factual prediction of future events.

You must not rely solely on the App for important life decisions or for decisions about your physical or mental health. Always consult an appropriately qualified professional for any concern about your health or wellbeing."""),
("5. Mental Health, Safety, and Crisis", """The App is not a crisis line and does not provide emergency services. It is not monitored in real time by clinicians or trained crisis responders.

If you are in immediate danger, having thoughts of harming yourself or another person, or otherwise in a mental health crisis, you must contact emergency services or a qualified crisis service in your country (for example, the Samaritans on 116 123 in the UK, or 988 in the US).

Any automated features that attempt to detect crisis-related content are best-effort, may fail, and must not be relied upon as a safety net."""),
("6. User Responsibilities", """You are solely responsible for:
• The content you create and store in the App
• Your decisions and actions based on App insights or AI-generated content
• Maintaining the confidentiality of your account
• Ensuring your use complies with these Terms and with applicable laws
• Seeking professional help when needed

You agree not to use the App for any unlawful purpose or in any way that could damage, disable, or impair the service."""),
("7. Privacy & Data Collection", """We collect and process your data to provide personalised experiences. This includes your birth details, journal entries and reflections, chat conversations with the AI, usage patterns and preferences, and device information.

Your data is encrypted and stored securely. We do not sell your personal information to third parties. For complete details, please review our Privacy Policy."""),
("8. AI-Generated Content", """The App uses artificial intelligence to generate insights, reflections, and responses. While we strive for helpfulness:
• AI responses may be inaccurate, incomplete, outdated, or inappropriate;
• AI cannot fully understand your unique circumstances, history, or context;
• Generated content should be evaluated critically and never acted on without independent judgement;
• The AI is not a replacement for human connection, professional support, or clinical care.

You acknowledge that AI output is generated probabilistically and that you bear sole responsibility for how you act on it."""),
("9. Subscriptions & Payments", """Astryn may be offered as an auto-renewing subscription via the Apple App Store. By subscribing:
• You authorise recurring charges to your Apple ID payment method;
• Subscriptions auto-renew at the end of each period unless cancelled at least 24 hours before the renewal date;
• You can manage or cancel your subscription at any time from your Apple ID settings;
• Refunds, where available, are handled by Apple under the App Store's refund policy;
• Prices may change with reasonable notice as permitted by the App Store.

Where an introductory free trial is offered, you will not be charged until the trial ends, and you can cancel at any time during the trial without being charged by cancelling at least 24 hours before the trial's end."""),
("10. Intellectual Property", """All content, features, and functionality of the App are owned by Eluma Labs Ltd and are protected by international copyright, trademark, and other intellectual property laws.

You retain ownership of the content you create within the App. By using the service, you grant us a license to process your content solely to provide and improve the service."""),
("11. Limitation of Liability", """To the maximum extent permitted by law, Eluma Labs Ltd and its officers, employees, agents, contractors, and partners shall not be liable for any direct, indirect, incidental, special, consequential, exemplary, or punitive damages of any kind, including but not limited to loss of profits, data, goodwill, or opportunities; service interruption or data loss; any damages arising from your reliance on App content or AI-generated output; and actions you take, or fail to take, based on content produced by the App.

You acknowledge that the App is provided on an "as is" and "as available" basis, without warranties of any kind, whether express or implied.

Nothing in these Terms excludes or limits liability for death or personal injury caused by our negligence, for fraud, or for any other liability that cannot be excluded or limited under applicable law."""),
("12. Indemnity", """You agree to indemnify and hold harmless Eluma Labs Ltd and its officers, employees, agents, contractors, and partners from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or relating to your use or misuse of the App, any breach by you of these Terms, or any decision or action you take based on App content."""),
("13. Termination", """We may suspend or terminate your access to the App at any time for violation of these Terms or for any other reason at our reasonable discretion. Upon termination, your right to use the App ceases immediately, and you may request export of your data within 30 days. Provisions that should survive termination, including limitation of liability and indemnity, will remain in effect."""),
("14. Changes to Terms", """We reserve the right to modify these terms at any time. We will notify users of significant changes through the App or via email. Your continued use of the App after changes constitutes acceptance of the new terms."""),
("15. Governing Law", """These Terms shall be governed by and construed in accordance with the laws of England and Wales. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts of England and Wales."""),
("16. Company Information", """Astryn is operated by Eluma Labs Ltd, a company registered in England and Wales.

Company Number: 17129588
Registered Address: 71-75 Shelton Street, Covent Garden, London, WC2H 9JQ
Contact: hello@elumahq.com"""),
("17. Contact", """If you have questions about these Terms and Conditions, please contact us at hello@elumahq.com"""),
]

PRIVACY = [
("1. Information We Collect", """When you use Astryn, we collect:
• Account Information: Email address and name when you sign up
• Birth Details: Date, time, and place of birth to calculate your natal chart
• Journal Entries: The content you write in your journal
• Chat Conversations: Messages exchanged with the AI companion
• Usage Data: How you interact with the app to improve our service
• Device Information: Device type, operating system, and app version"""),
("2. How We Use Your Information", """We use your information to:
• Calculate your birth chart and provide personalised cosmic guidance
• Generate AI-powered insights, reflections, and forecasts
• Improve and develop new features
• Send you notifications you've opted into
• Ensure the security and integrity of our service
• Comply with legal obligations"""),
("3. AI Processing", """Your birth details, journal entries, and conversations are processed by AI systems to generate insights. This processing:
• Uses third-party AI services with enterprise-grade security
• Does not use your data to train AI models
• Is essential to provide the core functionality of the app"""),
("4. Data Storage & Security", """We take the security of your data seriously:
• All data is encrypted in transit (TLS) and at rest (AES-256)
• We use secure cloud infrastructure with industry-standard protections
• Access to user data is strictly limited and logged
• Regular security updates are performed"""),
("5. Data Sharing", """We do not sell your personal data. We only share data with:
• Service Providers: Essential services like hosting, AI processing, and payment processing (Apple)
• Legal Requirements: When required by law or to protect our rights"""),
("6. Your Rights", """Under UK GDPR, you have the right to access, rectify, erase, and export your data, to object to certain processing, and to withdraw consent at any time.

To exercise these rights, use the Settings page in the app or contact us at hello@elumahq.com."""),
("7. Data Retention", """We retain your data for as long as your account is active. When you delete your account, personal data is deleted within 30 days, anonymised analytics may be retained, and backup deletion occurs within 90 days."""),
("8. Children's Privacy", """Astryn is not intended for children under 18. We do not knowingly collect data from children. If you believe a child has provided us with personal data, please contact us immediately."""),
("9. International Transfers", """Your data may be processed in countries outside the UK/EEA. When this occurs, we ensure appropriate safeguards are in place, including Standard Contractual Clauses approved by the UK ICO."""),
("10. Changes to This Policy", """We may update this Privacy Policy from time to time. We will notify you of significant changes through the app or via email. Your continued use after changes constitutes acceptance."""),
("11. Contact Us", """For any privacy-related questions or to exercise your rights, contact us:

Eluma Labs Ltd
Company Number: 17129588
71-75 Shelton Street, Covent Garden
London, WC2H 9JQ
United Kingdom

Email: hello@elumahq.com"""),
]

NAV = """<header class="nav">
  <div class="wrap">
    <a class="brand" href="/index.html"><img src="/astryn-logo.png" alt="Astryn logo"/><span>ASTRYN</span></a>
    <button class="nav-toggle" aria-label="Menu">&#9776;</button>
    <nav class="nav-links">
      <a href="/index.html#features">Features</a>
      <a href="/index.html#how">How it works</a>
      <a href="/index.html#safety">Safety</a>
      <a href="/support.html">Support</a>
      <a class="nav-cta" href="#get">Get the app</a>
    </nav>
  </div>
</header>"""

FOOTER = """<footer class="site">
  <div class="wrap">
    <div class="cols">
      <div>
        <a class="brand" href="/index.html"><img src="/astryn-logo.png" alt="Astryn logo"/><span>ASTRYN</span></a>
        <p class="tagline">Personal astrology from your own birth chart, guided moon rituals, and a guide who remembers your story.</p>
      </div>
      <div class="links">
        <div>
          <h4>Product</h4>
          <a href="/index.html#features">Features</a>
          <a href="/index.html#how">How it works</a>
          <a href="/index.html#moon">Moon Rituals</a>
        </div>
        <div>
          <h4>Help</h4>
          <a href="/support.html">Support</a>
          <a href="/index.html#safety">Safety</a>
          <a href="mailto:hello@elumahq.com">hello@elumahq.com</a>
        </div>
        <div>
          <h4>Legal</h4>
          <a href="/privacy.html">Privacy Policy</a>
          <a href="/terms.html">Terms of Service</a>
        </div>
      </div>
    </div>
    <div class="legal">
      Astryn is a product of Eluma Labs Ltd, a company registered in England and Wales (No. 17129588),
      71-75 Shelton Street, Covent Garden, London, WC2H 9JQ.<br/>
      &copy; 2026 Eluma Labs Ltd. All rights reserved.
    </div>
  </div>
</footer>"""

HEAD_COMMON = f"""<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta name="theme-color" content="#ffffff"/>
<link rel="icon" href="/astryn-logo.png"/>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"/>
<link rel="stylesheet" href="/style.css?v={CSS_VER}"/>"""


def page(title, body, description=""):
    desc = f'<meta name="description" content="{html.escape(description)}"/>' if description else ""
    return f"""<!doctype html>
<html lang="en">
<head>
<title>{html.escape(title)}</title>
{desc}
{HEAD_COMMON}
</head>
<body>
<canvas class="sky-canvas" aria-hidden="true"></canvas>
<div class="aurora" aria-hidden="true"><span class="blob b1"></span><span class="blob b2"></span><span class="blob b3"></span><span class="blob b4"></span></div>
{NAV}
{body}
{FOOTER}
<script src="/app.js?v={JS_VER}" defer></script>
</body>
</html>
"""


def legal_page(title, updated, sections, commitment=None):
    parts = ['<main class="legal"><div class="wrap"><div class="doc">',
             '<a class="back-link" href="/index.html">&#8592; Back to Astryn</a>',
             f'<h1>{html.escape(title)}</h1>',
             f'<div class="updated">Last updated: {html.escape(updated)}</div>']
    if commitment:
        parts.append(f'<div class="commitment">{html.escape(commitment)}</div>')
    for heading, body in sections:
        parts.append(f'<h2>{html.escape(heading)}</h2>')
        parts.append(f'<p>{html.escape(body)}</p>')
    parts.append('</div></div></main>')
    return page(f"Astryn — {title}", "\n".join(parts), description=f"{title} for Astryn by Eluma Labs Ltd.")


PILLARS = [
    ("&#9728;", "Your personal astrologer", "A guide that understands your chart and speaks to you in plain language, never horoscopes written for millions."),
    ("&#10022;", "The cosmos, applied to your life", "Astryn brings the context of the universe into the real events of your days, your intentions, and your rituals."),
    ("&#9789;", "Astrology meets your journal", "Write your day and Astryn aligns it with the stars, building a deeper, truer picture of who you are over time."),
]

FEATURES = [
    ("Your Cosmic Portrait", "&#9737;",
     "Astryn turns your birth chart into a personal guide. Built from your exact date, time, and place of birth, it reads the sky the way it touches you, then puts it into plain, useful language. No vague horoscopes written for millions of people. Just you, your chart, and the cosmos.",
     ["Calculated from your exact birth moment", "Planets, houses, and aspects in plain language", "No generic sun-sign horoscopes"]),
    ("Your Daily Reading", "&#9788;",
     "Each morning, Astryn blends your birth chart with today's transits to write a fresh daily insight. Read it as a prompt to reflect on, not a fixed prediction. Your daily reading and your weekly report are included with your subscription.",
     ["A fresh insight every morning", "Your chart plus today's transits", "A prompt to reflect, not a prediction"]),
    ("Your Weekly Forecast", "&#9784;",
     "Your weekly forecast reads the coming seven days against your chart and lays out an overview, the key days to watch, a personal focus, and an intention to carry through the week. A calendar maps the month's biggest sky events so you always know what is coming.",
     ["Overview, key days, and a weekly focus", "An intention to carry through the week", "A calendar of retrogrades, eclipses, and moons"]),
    ("Talk to Astryn", "&#10024;",
     "Ask anything. Astryn answers from your chart and remembers your journal, so the conversation gets more personal over time. Whether you want to understand a placement, prepare for a hard day, or just think something through, it is there to talk.",
     ["Answers grounded in your chart", "Remembers your journal", "More personal over time"]),
    ("Journal &amp; Reflection", "&#9998;",
     "Write freely or use guided templates. Astryn can reflect on your entries, drawing quiet connections between what you feel and what the sky is doing. Over time it builds a deeper, more accurate picture of who you are.",
     ["Free writing or guided templates", "Reflections that connect feeling and sky", "A truer picture of you over time"]),
    ("Bonds &amp; Constellations", "&#10022;",
     "Compatibility readings compare two full charts and show where you flow, where you spark, and where you can grow together. Save the people in your life as Bonds, then gather them into Constellations, your family, your friends, your team, to see the shared strengths and dynamics of a whole group.",
     ["Compare two full charts, side by side", "Constellations map family, friends, or teams", "Save people and revisit their readings anytime"]),
]


def landing():
    pillars = "\n".join(
        f'<div class="pillar reveal"><div class="glyph">{g}</div><h3>{t}</h3><p>{d}</p></div>'
        for g, t, d in PILLARS
    )
    features = []
    for title, glyph, body, items in FEATURES:
        lis = "".join(f"<li>{i}</li>" for i in items)
        features.append(f"""<div class="feature reveal">
        <div class="feature-text">
          <h3>{title}</h3>
          <p>{body}</p>
          <ul>{lis}</ul>
        </div>
        <div class="feature-media"><div class="big-glyph">{glyph}</div></div>
      </div>""")
    features_html = "\n".join(features)

    body = f"""<main>
  <section class="hero">
    <div class="wrap">
      <img class="hero-badge" src="/astryn-logo.png" alt="Astryn app icon"/>
      <span class="eyebrow">Your personal astrologer</span>
      <h1>Astrology that is<br/><em class="grad-text">actually about you.</em></h1>
      <p class="lead">Astryn is your own personal astrologer, bringing together your birth chart and the moving sky with the real events of your life. Journal your days, intentions, and rituals, and Astryn aligns them with the stars.</p>
      <div class="hero-cta" id="get">
        <a class="btn btn-primary" href="#get">Begin your free trial</a>
        <a class="btn btn-ghost" href="/index.html#features">Explore features</a>
      </div>
      <p class="hero-note">Made with care by Eluma Labs Ltd. Your data stays yours.</p>
    </div>
  </section>

  <section class="block" id="pillars">
    <div class="wrap">
      <div class="section-head reveal">
        <span class="eyebrow">Why Astryn</span>
        <h2>The universe, brought into your life</h2>
        <p>Astryn brings together your birth chart and the universe with the real events of your life, then helps you bring your days into line with the sky.</p>
      </div>
      <div class="pillars">{pillars}</div>
    </div>
  </section>

  <section class="block" id="features">
    <div class="wrap">
      <div class="section-head reveal">
        <span class="eyebrow">What's inside</span>
        <h2>Everything, personalised</h2>
        <p>Not one-size-fits-all horoscopes. Guidance computed from your unique sky, woven into your daily life.</p>
      </div>
      {features_html}
    </div>
  </section>

  <section class="block" id="moon">
    <div class="wrap">
      <div class="feature reveal">
        <div class="feature-text">
          <h3>Guided Moon Rituals</h3>
          <p>Lunar guidance and gentle rituals for every phase help you work with the Moon's rhythm rather than against it, from setting intentions on the new moon to releasing what no longer serves you on the full. When you are ready to let something go, write it down and burn it away on the fire and release board.</p>
          <ul>
            <li>Live phase and a guided ritual for every phase</li>
            <li>Set intentions on the new moon</li>
            <li>A fire and release board to burn what no longer serves you</li>
          </ul>
        </div>
        <div class="feature-media">
          <div class="moon-stage"><div class="moon"><div class="moon-shadow"></div></div></div>
        </div>
      </div>
    </div>
  </section>

  <section class="block" id="how">
    <div class="wrap">
      <div class="section-head reveal">
        <span class="eyebrow">How it works</span>
        <h2>From your birth moment to daily guidance</h2>
        <p>Astryn is built around your real chart. Here's the journey from first launch onward.</p>
      </div>
      <div class="steps">
        <div class="step reveal"><div class="step-no">1</div><h3>Share your birth moment</h3><p>Enter your date, time, and place of birth. Astryn computes a precise natal chart, the exact sky at the moment you arrived.</p></div>
        <div class="step reveal"><div class="step-no">2</div><h3>Meet your Cosmic Portrait</h3><p>See your planets, houses, and aspects explained in plain language, the blueprint behind everything Astryn tells you.</p></div>
        <div class="step reveal"><div class="step-no">3</div><h3>Live by the sky</h3><p>Daily and weekly forecasts personalised to your chart, plus a guided ritual for each moon phase as it turns.</p></div>
        <div class="step reveal"><div class="step-no">4</div><h3>Reflect and connect</h3><p>Journal with cosmic-aware prompts, explore compatibility with the people you love, and talk to a guide who remembers your story.</p></div>
      </div>
    </div>
  </section>

  <section class="block safety-section" id="safety">
    <div class="wrap">
      <div class="safety-header reveal">
        <h2>Safety, built in</h2>
        <a href="/privacy.html" class="btn btn-ghost">Learn more</a>
      </div>
      <div class="safety-grid">
        <div class="safety-card reveal">
          <div class="safety-icon">
            <svg viewBox="0 0 100 100">
              <path d="M50 10 L85 25 L85 50 C85 72 68 88 50 95 C32 88 15 72 15 50 L15 25 Z"/>
              <rect x="38" y="42" width="24" height="20" rx="3"/>
              <path d="M42 42 L42 35 C42 30 46 26 50 26 C54 26 58 30 58 35 L58 42"/>
              <circle cx="50" cy="52" r="3"/>
              <line x1="50" y1="55" x2="50" y2="58"/>
            </svg>
          </div>
          <h3>End-to-end encryption</h3>
          <p>Your birth details, journal entries, and conversations are encrypted in transit and at rest. Only you can access your data.</p>
        </div>
        <div class="safety-card reveal">
          <div class="safety-icon">
            <svg viewBox="0 0 100 100">
              <circle cx="50" cy="35" r="15"/>
              <path d="M25 85 C25 65 35 55 50 55 C65 55 75 65 75 85"/>
              <line x1="15" y1="15" x2="85" y2="85"/>
              <circle cx="50" cy="50" r="40" stroke-dasharray="8 4"/>
            </svg>
          </div>
          <h3>Your data, never sold</h3>
          <p>We will never sell, share, or use your personal data for advertising. Your reflections remain private.</p>
        </div>
        <div class="safety-card reveal">
          <div class="safety-icon">
            <svg viewBox="0 0 100 100">
              <ellipse cx="50" cy="50" rx="35" ry="20"/>
              <ellipse cx="50" cy="50" rx="35" ry="20" transform="rotate(60 50 50)"/>
              <ellipse cx="50" cy="50" rx="35" ry="20" transform="rotate(120 50 50)"/>
              <circle cx="50" cy="50" r="8"/>
            </svg>
          </div>
          <h3>Thoughtful guardrails</h3>
          <p>Your guide is designed with wellbeing in mind. Built-in safeguards keep every interaction supportive and responsible.</p>
        </div>
      </div>
    </div>
  </section>

  <section class="block" id="membership">
    <div class="wrap">
      <div class="section-head reveal">
        <span class="eyebrow">Membership</span>
        <h2>One subscription, everything included</h2>
        <p>Start with a free trial to explore everything, and cancel anytime before it ends without being charged.</p>
      </div>
      <div class="tiers">
        <div class="tier reveal">
          <h3>Astryn Light</h3>
          <p class="tier-cycle">Monthly</p>
          <p>Full access to every feature with a monthly allowance of Lumes, ideal if you dip in day to day.</p>
        </div>
        <div class="tier reveal tier-featured">
          <span class="tier-badge">Most Lumes</span>
          <h3>Astryn Universe</h3>
          <p class="tier-cycle">Monthly</p>
          <p>The same full access with a larger monthly allowance of Lumes, for when Astryn is part of your daily ritual.</p>
        </div>
      </div>
      <p class="tiers-note reveal">Every subscription includes full access to all features, Journal, Chat, Weekly and Daily forecasts, Birth Chart, and Lunar and Cosmic weather, plus a monthly allowance of Lumes that power your chats, lunar guidance, journal reflections, and compatibility readings. Two tiers let you pick the allowance that fits how you use Astryn, and you can top up anytime with in-app purchases. Purchased Lumes do not expire.</p>
    </div>
  </section>

  <section class="cta-band" id="download">
    <div class="wrap reveal">
      <h2>Astrology that is actually about you</h2>
      <p>Whether you are brand new to astrology or have read charts for years, Astryn meets you where you are and grows with you. Begin your free trial and explore everything.</p>
      <a class="btn btn-primary" href="#get">Begin your free trial</a>
    </div>
  </section>

  <section class="block sub-legal">
    <div class="wrap">
      <div class="sub-legal-box reveal">
        <h3>Subscription details</h3>
        <p>Astryn offers auto-renewable subscriptions: <strong>Astryn Light (monthly)</strong> and <strong>Astryn Universe (monthly)</strong>. A free trial is available to eligible new subscribers.</p>
        <p>Payment is charged to your Apple ID at confirmation of purchase. Your subscription automatically renews at the standard price unless it is cancelled at least 24 hours before the end of the current period. Your account is charged for renewal within 24 hours before the end of the current period. If a free trial is offered, any unused portion of the trial is forfeited when you purchase a subscription, where applicable.</p>
        <p>You can manage or cancel your subscription, and turn off auto-renewal, in your Apple ID Account Settings at any time after purchase. You can delete your account at any time within the app from the settings page.</p>
        <p><a href="/terms.html">Terms of Use (EULA)</a> &nbsp;&middot;&nbsp; <a href="/privacy.html">Privacy Policy</a></p>
      </div>
    </div>
  </section>
</main>"""
    return page("Astryn — Personal Astrology & Guided Moon Rituals", body,
                description="Astryn is personal astrology from your own birth chart, with daily and weekly forecasts, guided moon rituals, and a guide who remembers your story.")


SUPPORT_FAQ = [
    ("What is Astryn?",
     "Astryn is a personal astrology app. It calculates your natal chart from your exact birth details, then gives you daily and weekly guidance, guided moon rituals, journaling, compatibility insights, and an AI guide that remembers your story. It is made for self-reflection, curiosity, and entertainment."),
    ("How does Astryn create my readings?",
     "Everything starts with your birth chart, computed from the date, time, and place you were born. Your forecasts and insights are drawn from that chart and the current positions of the planets and moon, so they are personal to you rather than generic sun-sign horoscopes."),
    ("What are Lumes?",
     "Lumes are Astryn's in-app currency. You use them for deeper experiences such as extended conversations with your guide and certain premium readings. Subscribers receive a regular allowance of Lumes."),
    ("What are guided moon rituals?",
     "Astryn tracks the live phase of the moon and offers one thoughtful ritual to match, intention-setting around the new moon, release around the full moon, and gentle reflection in between. There is also a fire-and-release board for letting things go."),
    ("What are Bonds and Constellations?",
     "Bonds let you add the people who matter and explore the dynamics between your charts. Constellations group several people, such as a family, friendship circle, or team, to reveal shared strengths, roles, and gaps."),
    ("Is my data private?",
     "Yes. Your birth details, journal entries, and conversations are encrypted in transit and at rest. We do not sell your data, share it for advertising, or use it to train public AI models. For full details, see our <a href=\"/privacy.html\">Privacy Policy</a>."),
    ("Is there a free trial?",
     "Astryn may offer an introductory free trial on its subscription. You will not be charged until the trial ends, and you can cancel any time during the trial, at least 24 hours before it ends, without being charged."),
    ("How do I manage or cancel my subscription?",
     "Subscriptions are billed through your Apple ID and can be managed there. On your iPhone or iPad go to Settings, tap your name, then Subscriptions to view, change, or cancel."),
    ("Can I export my data?",
     "Yes. You can export your journal entries and personal data from the Settings screen in the app. Your reflections belong to you."),
    ("The app isn't working properly. What should I do?",
     "First, close and reopen the app. If the issue continues, make sure you have the latest version from the App Store. If it still happens, email us with a description of the problem and your device model and we'll help."),
    ("How do I delete my account?",
     "You can delete your account and all associated data from the Settings screen in the app. Alternatively, contact us and we will process your request within 48 hours."),
]


def support_page():
    about = """<div class="app-info">
      <div class="app-info-item"><h4>Developer</h4><p>Eluma Labs Ltd</p></div>
      <div class="app-info-item"><h4>Platform</h4><p>iOS</p></div>
      <div class="app-info-item"><h4>Category</h4><p>Lifestyle</p></div>
    </div>"""
    faqs = "\n".join(
        f'<div class="faq-item reveal"><h3>{q}</h3><p>{a}</p></div>'
        for q, a in SUPPORT_FAQ
    )
    body = f"""<main class="support">
  <div class="wrap">
    <div class="doc">
      <a class="back-link" href="/index.html">&#8592; Back to Astryn</a>
      <div class="section-head" style="text-align:left;margin-bottom:32px">
        <span class="eyebrow">Support</span>
        <h2>How can we help?</h2>
        <p>Answers to common questions, and a direct line to us if you need more.</p>
      </div>

      <h2 class="sec">About the app</h2>
      {about}

      <h2 class="sec">Frequently asked questions</h2>
      {faqs}

      <h2 class="sec">Contact us</h2>
      <p>Can't find what you're looking for? We're happy to help, and typically reply within 24-48 hours.</p>
      <div class="contact-box reveal">
        <h3>Email support</h3>
        <p>We usually respond within one to two working days.</p>
        <a href="mailto:hello@elumahq.com">hello@elumahq.com</a>
      </div>
    </div>
  </div>
</main>"""
    return page("Astryn — Support", body,
                description="Support and FAQs for Astryn, a personal astrology app by Eluma Labs Ltd.")


def main():
    with open("index.html", "w") as f:
        f.write(landing())
    with open("privacy.html", "w") as f:
        f.write(legal_page("Privacy Policy", PRIVACY_UPDATED, PRIVACY, PRIVACY_COMMITMENT))
    with open("terms.html", "w") as f:
        f.write(legal_page("Terms of Service", TERMS_UPDATED, TERMS))
    with open("support.html", "w") as f:
        f.write(support_page())
    print("Generated index.html, privacy.html, terms.html, support.html")


if __name__ == "__main__":
    main()
